when I try to run the following code: (base) [xid40@gpu-stage06 PyTorch-VAE]$ python run.py -c configs/vae.yaml

I got the following error, it looks like I did not get GPU allocated, although I am in GPU mode

pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [1]

But your machine only has: [0]

Comments
Submitted by FANGPING on Mon, 01/03/2022 - 18:09 Permalink

new
Assigned: unassigned -> xid40
Client: -> support
State: -> active
Priority: -> normal
I believe that the error message is self-explanatory. Your configuration file has specified gpus: [1]. When you requested a single GPU card, the gpu index is 0.

trainer_params:
gpus: [0]

